version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file: ./backend/.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=${REDIS_URL} 
      - MONGO_URI=${MONGO_URI}
      - FRONTEND_URL=${FRONTEND_URL}

  frontend:
    build: ./frontend
    ports:
      - "5173:80" 
    environment:
      - VITE_APP_BACKEND_URL=${VITE_APP_BACKEND_URL}
    depends_on:
      - backend